Welthungerhilfe/cgm-rg

- src/result_gen.py
- src/utils/inference.py
- tests/test_preprocessing.py
Fixed the argparser to read the model_id and service from argparse.
Fixed other minor improvements.
> Added argparser to read input argumets

- src/result_gen.py
- src/utils/preprocessing.py
- src/utils/rgutils.py
Added code to generate pose results for all rgb artifacts, delete the artifacts when all the processes are completed
release https://dev.azure.com/cgmorg/ChildGrowthMonitor/_releaseProgress?_a=release-pipeline-progress&releaseId=57
> Us405 develop

- Dockerfile
Modified docker for release of Result Generation
> Added dockerfile for release

- src/result_gen.py
- src/utils/preprocessing.py
- src/utils/rgutils.py
- tests/test_result_gen.py
added code to update face blurred artifacts in db, test case for checking result generation
https://dev.azure.com/cgmorg/ChildGrowthMonitor/_releaseProgress?_a=release-environment-logs&releaseId=63&environmentId=156
> Us406 develop

- deployment/crontab
- requirements.txt
- src/get_and_post_worflow.py
- src/result_gen_with_api.py
- src/utils/inference.py
- src/utils/preprocessing.py
- src/workflows/height-workflow.json
- added code to do height prediction
- height prediction done locally in container
-
> Us 715 height prediction

- src/api_endpoints.py
- src/get_and_post_worflow.py
- src/result_gen_with_api.py
https://dev.azure.com/cgmorg/ChildGrowthMonitor/_workitems/edit/797
e.g. Before /api/scan/scans/unprocessed?limit=1
After Api changes /api/scans/unprocessed?limit=1
> Us 797 sandbox auth

- deployment/crontab
- entrypoint_with_api.sh
- requirements.txt
- src/api_endpoints.py
- src/download_model.py
- src/get_and_post_worflow.py
- src/result_gen_with_api.py
- src/utils/inference.py
- src/utils/preprocessing.py
- src/workflows/standing_laying-workflow.json
Standing/laying added in RG
locally
> Standing/laying classifier added in result generation #26

- requirements.txt
- src/api_endpoints.py
- src/get_and_post_worflow.py
- src/result_gen_with_api.py
- src/result_generation/height.py
- src/result_generation/utils.py
- src/result_generation/weight.py
USER STORY- 
https://dev.azure.com/cgmorg/ChildGrowthMonitor/_workitems/edit/671
FOR HEIGHT & WEIGHT
- Personal details extracted from Person API
- Utils added in result generation
- Age functionality added
- zscore calculated and diagnosis computed
View
>  Zscore PyPI library to compute diagnosis

- src/api_endpoints.py
- src/get_and_post_worflow.py
- src/result_gen_with_api.py
- src/workflows/weight-workflow-scan.json
> Add prod endpoint

- Dockerfile
- src/api_endpoints.py
- src/get_and_post_worflow.py
- src/result_gen_with_api.py
Improvements: Deployment for cgm-rg for any new environment without changing in the code.
> Refactoring

- tests/set_up_dummy_objects.py
- fixed error when testing height_flow after adding code for MCNN
> added parameter for MCNN model in dummy height object

- src/workflows/height-plaincnn-workflow-artifact.json
- src/workflows/height-plaincnn-workflow-scan.json
- src/workflows/standing_laying-workflow.json
- Height model renamed
- Standing/laying model renamed
> Model renamed

- codecov.yml
Codecov comment removed because it is not much helpful.
> codecov comment removed

- src/result_gen_with_api.py
- src/result_generation/blur.py
- tests/set_up_dummy_objects.py
- tests/set_up_dummy_variables.py
- tests/test_blur_flow.py
> Scan version support

- src/api_endpoints.py
- src/result_gen_with_api.py
- tests/set_up_dummy_objects.py
- tests/set_up_dummy_variables.py
This code is for evaluation of Height Multi Artifact CNN model on scan version v0.9 in cgm-rg.
> Multi Artifact CNN eval on v0.9

- requirements.txt
- src/download_model.py
- src/result_gen_with_api.py
- src/result_generation/height/height.py
- src/result_generation/height/height_ensemble.py
- src/utils/inference.py
- src/workflows/height-ensemble-workflow-artifact.json
- src/workflows/height-ensemble-workflow-scan.json
US :- https://dev.azure.com/cgmorg/ChildGrowthMonitor/_workitems/edit/1203
- prediction and uncertainty in tagging tool
scan level: 
**q1-ensemble-warmup-mean** - prediction - uncertainty
- artifact-level
**q1-ensemble-warmup**   prediction -uncertainty
> Deepensemble in cgm-rg

- src/download_model.py
- src/result_gen_with_api.py
- src/result_generation/height/height.py
- src/result_generation/height/height_rgbd.py
- src/utils/preprocessing.py
> Refactor more

- src/result_gen_with_api.py
- src/result_generation/height/height.py
- src/result_generation/height/height_ensemble.py
- src/result_generation/height/height_rgbd.py
- tests/set_up_dummy_objects.py
- tests/set_up_dummy_variables.py
- tests/test_height_flow.py
- tests/test_preprocessing.py
- tests/test_weight_flow.py
- make rgb_artifacts parameter in heightFlow optional
- stop using rgbd model until it is fixed
- fix tests as per changes made above
- every model should have run_flow() method
> Fix height model arguments error

- src/result_gen_with_api.py
- src/result_generation/height/height_rgbd.py
- added rgbd workflow fixing errors with path
- checking scan version before running rgbd(only for v0.9)
> Fix error in rgbd

- src/result_gen_with_api.py
This branch adds the logic to process the old_scan on rgbd scan for version v0.9.
>  Adding logic for processing scans v0.9

- src/api_endpoints.py
- Added endpoint to get unprocessed scans filterd by scan version and workflow id
- Added changes in api requests to get the scans  filtered by scan version and workflow id
> Rgbd eval workflow id v0.9

- .flake8
- .github/workflows/continous-integration.yml
- tests/test_blur_flow.py
- tests/test_height_flow.py
- tests/test_result_generation.py
- tests/test_weight_flow.py
Changes:
- Fix flake8 violations in tests/ dir
> Activate flake8 checks in tests/ dir

- src/api_endpoints.py
- src/download_model.py
- src/result_gen_with_api.py
Removed RGBD code
Commented out Deep Ensemble worflow
Cleaned code which is not used.
> Remove rgbd code

- ci/azure-pipelines.yml
Solved the issue with the empty published stage variable "TAG" by adding the stage, which publishes this variable, as dependency in the stage, which wants to access it.
To access published stage variables the stage has to be added under "dependsOn".
Also added some echo debug lines to the scripts/tasks.
> Pipeline bug

- .github/workflows/continous-integration.yml
- CI should not fail if upload codecov fails
> dont fail if upload codecov fails

- requirements.txt
- src/get_scan_metadata.py
- src/prepare_artifacts.py
- src/process_workflows.py
- src/result_gen_with_api.py
Retroactive Evaluation of old scans on the new workflow ids
CR link
[Process the retroactive scans from the queue on the new workflow](https://dev.azure.com/cgmorg/ChildGrowthMonitor/_workitems/edit/1309)
> Retroactive scan eval

- ci/azure-pipelines.yml
- src/result_gen_with_api.py
This PR does below two tasks.
Enable INBMZ and NUNAM environment in Azure deployment pipeline
Disable Retroactive evaluation of scans
> Enable prod env

- src/result_gen_with_api.py
Motivation:
Run evaluation of retroactive scans on the newly registered workflow
CR link:
https://dev.azure.com/cgmorg/ChildGrowthMonitor/_workitems/edit/1295
> Added code to perform retroactive evaluation

- src/workflows/blur-workflow.json
Hotfix to update the version of blur workflow due to addition of no of faces
> updated version of blur workflow due to addition of no of faces

- src/download_model.py
Model Registered: 
- Height
- Weight
- RGBD
- HRNet
- M-CNN Height
> shifting model from west europe to central india

- src/result_gen_with_api.py
- src/result_generation/height/height.py
- src/workflows/height-plaincnn-workflow-artifact.json
- src/workflows/height-plaincnn-workflow-scan.json
- PR  to debug the functioning of new height model for retroactive workflow
- removed median from mean results model
> debugging retroactive flow of cgm-rg

- src/utils/inference.py
- src/workflows/height-plaincnn-workflow-artifact.json
- src/workflows/height-plaincnn-workflow-scan.json
[New height model](https://ml.azure.com/model/standing_laying_classifier:1/details?wsid=/subscriptions/9b5bbfae-d5d1-4aae-a2ca-75159c0c887d/resourceGroups/cgm-ml-prod-ci-rg/providers/Microsoft.MachineLearningServices/workspaces/cgm-ml-prod-ci-azml&tid=3a27c573-ec1a-4734-9cd3-3208af51794b)
Path changed
> New version of Height model register 

- src/result_generation/height/height_rgbd.py
Changes: 
- sort import
- polish imports to fit code on less lines
- Add whitespace to semantically structure into code blocks
> Refactor height RGBD

- .github/workflows/continous-integration.yml
- requirements.txt
- src/api_endpoints.py
- src/error_stats_api_endpoints.py
- src/result_gen_with_api.py
- src/result_generation/height/height.py
- src/result_generation/height/height_plaincnn.py
- src/result_generation/height/height_rgbd.py
- tests/set_up_dummy_objects.py
- tests/set_up_dummy_variables.py
- tests/test_height_flow.py
Percentile error stats at scan level and artifact level added.
Error Stats API Used for getting pos_percenetile, negative percentile and made
At scan level max of pos_percentile, min of negative percentile and median of mae done.
Working now for:-
1. HeightPlainCNN Depthmap Model
2. Height RGBD Model.
> Percentile Error Stats added

- src/workflows/weight-workflow-artifact.json
- src/workflows/weight-workflow-scan.json
> Added workflow with correct name

- src/utils/preprocessing.py
- src/workflows/standing_laying-workflow.json
#170 
1. Bug removed from standing laying.
2. Version updated.
> Standing-laying Bug Removed

- ci/azure-pipelines.yml
https://dev.azure.com/cgmorg/ChildGrowthMonitor/_workitems/edit/2474
updating main branch pipeline to ignore all branches containing code for ml_rg
> updated pipeline code to exclude ml_rg branch

- ci/azure-pipelines.yml
- requirements.txt
> Py37 pipeline
